# Generated by Django 5.1.5 on 2025-02-12 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gourmandprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='gourmandprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='gourmandprofile',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='owners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])], verbose_name='Фото владельца'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='places',
            field=models.ManyToManyField(blank=True, to='landing.place'),
        ),
    ]
