# Generated by Django 5.1.5 on 2025-01-29 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gourmand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='landing.gourmand'),
            preserve_default=False,
        ),
    ]
