# Generated by Django 5.1.5 on 2025-03-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_event_cloud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cloud',
        ),
    ]
