# Generated by Django 5.1.5 on 2025-02-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_remove_gourmandprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
