# Generated by Django 5.1.5 on 2025-02-25 10:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_alter_review_gourmand_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='gourmand_rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='negative_rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='positive_rating',
            field=models.DecimalField(blank=True, decimal_places=0, default=None, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])], verbose_name='Фото отзыва')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landing.review')),
            ],
        ),
    ]
