# Generated by Django 5.1.5 on 2025-02-13 14:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_ownerprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gourmand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])], verbose_name='Изображение события')),
                ('place', models.ManyToManyField(to='landing.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
