# Generated by Django 5.1.5 on 2025-02-07 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_alter_event_image_alter_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gourmand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gourmands/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])], verbose_name='Фото гурмана'),
        ),
    ]
