# Generated by Django 5.1.5 on 2025-02-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_gourmand'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.TextField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Gourmand',
        ),
    ]
