# Generated by Django 5.1.5 on 2025-02-07 06:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_gourmand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'webp'])], verbose_name='Фото отзыва'),
        ),
    ]
