# Generated by Django 5.1.5 on 2025-02-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='gourmand_rating',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=10),
            preserve_default=False,
        ),
    ]
