# Generated by Django 5.1.5 on 2025-02-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_review_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gourmand', 'Гурман'), ('owner', 'Владелец заведения')], default='gourmand', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
