# Generated by Django 5.1.5 on 2025-03-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
