# Generated by Django 5.1.5 on 2025-03-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_place_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gourmandprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gourmandprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gourmand_images/'),
        ),
        migrations.AlterField(
            model_name='gourmandprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews', to='landing.place'),
        ),
    ]
