# Generated by Django 5.1.5 on 2025-03-13 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_alter_gourmandprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='places',
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='landing.place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='landing.place'),
        ),
    ]
