# Generated by Django 5.1.5 on 2025-03-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cloud',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
    ]
