# Generated by Django 5.1.5 on 2025-03-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_npstag_npsresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='npstag',
            name='label',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
