# Generated by Django 5.1.5 on 2025-03-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_event_slug_alter_place_slug_alter_review_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default='temporary-slug', max_length=100, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='slug',
            field=models.SlugField(blank=True, default='temporary-slug', max_length=100, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(blank=True, default='temporary-slug', max_length=100, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, default='temporary-slug', max_length=100, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
