# Generated by Django 5.1.5 on 2025-03-25 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_alter_event_slug_alter_place_slug_alter_review_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='gourmand_rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
