# Generated by Django 5.1.5 on 2025-04-01 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_event_owner_alter_review_gourmand_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gourmand', 'Гурман'), ('owner', 'Владелец заведения')], db_index=True, default='gourmand', max_length=10),
        ),
    ]
